"""add fields for fdc data

Revision ID: 0bfc85f1c349
Revises: 9f5264b10694
Create Date: 2026-03-19 18:30:57.630351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfc85f1c349'
down_revision: Union[str, None] = '9f5264b10694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_portion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('measure_unit_name', sa.String(length=100), nullable=False),
    sa.Column('gram_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('food', sa.Column('fdc_id', sa.Integer(), nullable=True))
    op.add_column('food', sa.Column('brand_name', sa.String(length=255), nullable=True))
    op.add_column('food', sa.Column('data_type', sa.String(length=50), nullable=True))
    op.alter_column('food', 'calories_per_100g',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_food_brand_name'), 'food', ['brand_name'], unique=False)
    op.create_index(op.f('ix_food_fdc_id'), 'food', ['fdc_id'], unique=True)
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.alter_column('meal_entry', 'weight_grams',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_entry', 'weight_grams',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_index(op.f('ix_food_fdc_id'), table_name='food')
    op.drop_index(op.f('ix_food_brand_name'), table_name='food')
    op.alter_column('food', 'calories_per_100g',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('food', 'data_type')
    op.drop_column('food', 'brand_name')
    op.drop_column('food', 'fdc_id')
    op.drop_table('food_portion')
    # ### end Alembic commands ###