"""Add GamificationProfile

Revision ID: 62a123a993d4
Revises: c4a1b2d3e5f6
Create Date: 2026-05-10 13:42:57.042040

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62a123a993d4"
down_revision: str | None = "c4a1b2d3e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gamification_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("str_points", sa.Integer(), nullable=False),
        sa.Column("sta_points", sa.Integer(), nullable=False),
        sa.Column("agi_points", sa.Integer(), nullable=False),
        sa.Column("vit_points", sa.Integer(), nullable=False),
        sa.Column("wil_points", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gamification_profile_user_id"), "gamification_profile", ["user_id"], unique=True)
    op.create_unique_constraint(None, "exercise_muscle_group", ["exercise_id", "muscle_group_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exercise_muscle_group", type_="unique")
    op.drop_index(op.f("ix_gamification_profile_user_id"), table_name="gamification_profile")
    op.drop_table("gamification_profile")
    # ### end Alembic commands ###
