"""Remove rpg stats for time

Revision ID: 7f9cb4b13d2c
Revises: 62a123a993d4
Create Date: 2026-05-10 14:00:02.589205

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7f9cb4b13d2c"
down_revision: str | None = "62a123a993d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
