"""add oauth field to user

Revision ID: a8a162f13084
Revises: 9f5264b10694
Create Date: 2026-03-19 21:09:09.803436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a162f13084'
down_revision: Union[str, None] = '9f5264b10694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_provider', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('oauth_provider_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'oauth_provider_id')
    op.drop_column('user', 'oauth_provider')
    # ### end Alembic commands ###