"""make password not required and add fields for 2fa

Revision ID: e7aaf17b7cbd
Revises: a8a162f13084
Create Date: 2026-03-20 11:30:49.846094

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7aaf17b7cbd"
down_revision: str | None = "a8a162f13084"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("totp_secret", sa.String(length=32), nullable=True))
    op.add_column("user", sa.Column("is_2fa_enabled", sa.Boolean(), nullable=False, server_default="false"))
    op.alter_column("user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("user", "is_2fa_enabled")
    op.drop_column("user", "totp_secret")
    # ### end Alembic commands ###
