"""Application-wide constants."""

# Pagination defaults
DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MIN_PAGE = 1
MIN_PAGE_SIZE = 1
MAX_PAGE_SIZE = 100

# Rate limiting defaults
DEFAULT_RATE_LIMIT = 60
DEFAULT_RATE_WINDOW_SECONDS = 60
RATE_LIMIT_TTL_SECONDS = 3600  # 1 hour

# Token expiration
ACCESS_TOKEN_EXPIRE_MINUTES = 60
REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # 7 days
EMAIL_TOKEN_EXPIRE_MINUTES = 60 * 24  # 1 day
TWO_FA_TOKEN_EXPIRE_MINUTES = 5
TWO_FA_TOKEN_EXPIRE_SECONDS = TWO_FA_TOKEN_EXPIRE_MINUTES * 60

# Cache / OAuth TTLs
DEFAULT_CACHE_TTL_SECONDS = 300
OAUTH_STATE_TTL_SECONDS = 300

# Token generation lengths
REFRESH_TOKEN_BYTES = 64
OAUTH_STATE_TOKEN_BYTES = 32

# Minutes-to-seconds conversion
SECONDS_PER_MINUTE = 60
